### ISSUE TITLE
Create a skeleton Python project that can be used as a template

### ISSUE THREAD

**Issue by hoptek-labs** [hoptek-labs/python-cli-skeleton-app#1]
### Motivation

We want a skeleton Python project that can be used as a template.

It should have the following characteristics:
- Bare minimum set of libraries for linting, testing and configuration
- Standardised and reusable project structure

### User Story

**As a** Python developer
**I want to** be able to use a template skeleton Python CLI app
**So that** I can avoid project setup boilerplate when delivering business value

### Success Criteria

**Scenario:** Using this skeleton app to create a Python project
**Given** that I am a Python developer
**When** I use this skeleton app as a reference for my Python project
**Then** I can effortlessly setup my Python project in a standardised way

### Deliverables
- [x] #2
- [x] #3
- [x] #4
  - [x] First time setup - **Included in README**
  - ~~Start coding -- especially for feature branches~~
  - [x] Running the tests - **Included in README**
  - [x] Project structure description - **Included in README**

### Checklist
- [x] Defuzz date and participants: 2022-10-03 @codepozro and @hoptek-labs 
- [x] Demo date and participants: 2022-10-05 @codepozro and @hoptek-labs

**Comment by codepozro** [comment]
We will de-scope "Start coding -- especially for feature branches" so that we'll work on it as part of the Git basic workshop and Feature dev good practice workshop for the next two weeks.

**Comment by codepozro** [comment]
2022-10-05
Closing this epic as:

- All deliverables (#2, #3, #4) were demoed
- A demo of the work to the team will be done as part of the series of workshops
